// <auto-generated />
using System;
using GigaScramSoft;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GigaScramSoft.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250314063359_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GigaScramSoft.Model.ContentUnitImageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContentUnitId");

                    b.ToTable("ContentUnitImages");
                });

            modelBuilder.Entity("GigaScramSoft.Model.ContentUnitMainCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ContentUnitMainCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Operating Systems"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Development & Programming"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Security & Privacy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Multimedia & Design"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Productivity & Office Tools"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Networking & Internet"
                        });
                });

            modelBuilder.Entity("GigaScramSoft.Model.ContentUnitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DownloadLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PreviewImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("ContentUnits");
                });

            modelBuilder.Entity("GigaScramSoft.Model.ContentUnitSubCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId");

                    b.ToTable("ContentUnitSubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MainCategoryId = 1,
                            Name = "Windows Software"
                        },
                        new
                        {
                            Id = 2,
                            MainCategoryId = 1,
                            Name = "MacOS Software"
                        },
                        new
                        {
                            Id = 3,
                            MainCategoryId = 1,
                            Name = "Linux Software"
                        },
                        new
                        {
                            Id = 4,
                            MainCategoryId = 1,
                            Name = "Mobile Apps (Android, iOS)"
                        },
                        new
                        {
                            Id = 5,
                            MainCategoryId = 2,
                            Name = "IDE & Code Editors"
                        },
                        new
                        {
                            Id = 6,
                            MainCategoryId = 2,
                            Name = "Frameworks & Libraries"
                        },
                        new
                        {
                            Id = 7,
                            MainCategoryId = 2,
                            Name = "Database Management"
                        },
                        new
                        {
                            Id = 8,
                            MainCategoryId = 2,
                            Name = "Version Control & DevOps"
                        },
                        new
                        {
                            Id = 9,
                            MainCategoryId = 3,
                            Name = "Antivirus & Anti-Malware"
                        },
                        new
                        {
                            Id = 10,
                            MainCategoryId = 3,
                            Name = "VPN & Proxy Software"
                        },
                        new
                        {
                            Id = 11,
                            MainCategoryId = 3,
                            Name = "Password Managers"
                        },
                        new
                        {
                            Id = 12,
                            MainCategoryId = 3,
                            Name = "Encryption Tools"
                        },
                        new
                        {
                            Id = 13,
                            MainCategoryId = 4,
                            Name = "Photo & Image Editing"
                        },
                        new
                        {
                            Id = 14,
                            MainCategoryId = 4,
                            Name = "Video Editing & Production"
                        },
                        new
                        {
                            Id = 15,
                            MainCategoryId = 4,
                            Name = "Audio Editing & Music Production"
                        },
                        new
                        {
                            Id = 16,
                            MainCategoryId = 4,
                            Name = "3D Modeling & Animation"
                        },
                        new
                        {
                            Id = 17,
                            MainCategoryId = 5,
                            Name = "Office Suites"
                        },
                        new
                        {
                            Id = 18,
                            MainCategoryId = 5,
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = 19,
                            MainCategoryId = 5,
                            Name = "Note-Taking & Mind Mapping"
                        },
                        new
                        {
                            Id = 20,
                            MainCategoryId = 5,
                            Name = "PDF Tools"
                        },
                        new
                        {
                            Id = 21,
                            MainCategoryId = 6,
                            Name = "Browsers & Extensions"
                        },
                        new
                        {
                            Id = 22,
                            MainCategoryId = 6,
                            Name = "Download Managers"
                        },
                        new
                        {
                            Id = 23,
                            MainCategoryId = 6,
                            Name = "Remote Desktop & VPN"
                        },
                        new
                        {
                            Id = 24,
                            MainCategoryId = 6,
                            Name = "FTP & File Sharing"
                        });
                });

            modelBuilder.Entity("GigaScramSoft.Model.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@example.com",
                            Login = "admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEGLiW322/P8hJTxWa0SUJv0R/agf1XoFqzYySw2NR1o0NF2l6hU3murDZcKKWKEs3g==",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "user1@example.com",
                            Login = "user1",
                            PasswordHash = "AQAAAAIAAYagAAAAEGLiW322/P8hJTxWa0SUJv0R/agf1XoFqzYySw2NR1o0NF2l6hU3murDZcKKWKEs3g==",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "bob@example.com",
                            Login = "bob",
                            PasswordHash = "AQAAAAIAAYagAAAAEGLiW322/P8hJTxWa0SUJv0R/agf1XoFqzYySw2NR1o0NF2l6hU3murDZcKKWKEs3g==",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("GigaScramSoft.Model.UserRoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("GigaScramSoft.Model.ContentUnitImageModel", b =>
                {
                    b.HasOne("GigaScramSoft.Model.ContentUnitModel", "ContentUnit")
                        .WithMany("Images")
                        .HasForeignKey("ContentUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentUnit");
                });

            modelBuilder.Entity("GigaScramSoft.Model.ContentUnitModel", b =>
                {
                    b.HasOne("GigaScramSoft.Model.ContentUnitSubCategoryModel", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("GigaScramSoft.Model.ContentUnitSubCategoryModel", b =>
                {
                    b.HasOne("GigaScramSoft.Model.ContentUnitMainCategoryModel", "MainCategory")
                        .WithMany()
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("GigaScramSoft.Model.UserModel", b =>
                {
                    b.HasOne("GigaScramSoft.Model.UserRoleModel", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GigaScramSoft.Model.ContentUnitModel", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
